server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container'
      - source_labels: ['__meta_docker_container_label_com_docker_compose_service']
        target_label: 'service'
      - source_labels: ['__meta_docker_container_log_path']
        target_label: '__path__'
      - replacement: 'docker-logs'
        target_label: 'job'
    pipeline_stages:
      - docker: {}
      - match:
          selector: '{job="docker"} |~ "^{"'
          stages:
            - json:
                expressions:
                  level: level
                  msg: message
                  trace_id: trace_id
                  span_id: span_id
      - match:
          selector: '{job="docker"} !~ "^{"'
          stages:
            - regex:
                expression: '^(?:[\d-]+\s+[\d:.]+)?\s*(?P<level>\w+):?\s+(?P<msg>.*)$'
      - labels:
          level:
          trace_id:
          span_id:
          msg:
